import os
import sys
import numpy as np
import rustworkx as rx
from typing import Optional, List, Type

# Add the parent directory to sys.path so we can import pyalex
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from .embed import generate_embeddings
from .data_loader import load_graphml_to_rx, write_rx_to_graphml
from .interfaces import EntityEmbeddingStrategy
from .strategies.topological import AverageNeighborStrategy

def run_embedding_pipeline(
    graph: rx.PyDiGraph | rx.PyGraph,
    topological_strategy: Optional[EntityEmbeddingStrategy] = None,
    entity_types: Optional[List[str]] = None
) -> rx.PyDiGraph | rx.PyGraph:
    """
    Core pipeline to generate and assign embeddings to nodes in the given graph.
    
    Args:
        graph: A rustworkx graph generated by pyalex network build.
        topological_strategy: The strategy to use for embedding non-Work entities (e.g. AverageNeighborStrategy).
        entity_types: List of entity types to compute topological embeddings for (default: ["author", "institution"]).
        
    Returns:
        The mutated graph containing the embeddings.
    """
    if topological_strategy is None:
        topological_strategy = AverageNeighborStrategy()
        
    if entity_types is None:
        entity_types = ["author", "institution"]

    # 1. Generate textual embeddings for all Work-like nodes (source and external)
    print("\n--- Generating Textual Embeddings for Works ---")
    work_indices = []
    work_texts = []
    
    for node_idx in graph.node_indices():
        attrs = graph.get_node_data(node_idx)
        if attrs and attrs.get("type") in ("source", "external"):
            title = attrs.get("title", "")
            if title:
                work_indices.append(node_idx)
                work_texts.append(title)
                
    if work_texts:
        print(f"Embedding {len(work_texts)} work titles...")
        embeddings = generate_embeddings(work_texts)
        for node_idx, emb in zip(work_indices, embeddings):
            attrs = graph.get_node_data(node_idx)
            attrs["embedding"] = np.array(emb, dtype=np.float32)
            graph[node_idx] = attrs
        print("Work embeddings assigned.")
    else:
        print("No works found to embed.")

    # 2. Generate topological embeddings for other Entities
    print("\n--- Generating Topological Embeddings for Entities ---")
    
    for entity_type in entity_types:
        print(f"Computing embeddings for {entity_type}s...")
        entity_embeddings = topological_strategy.compute_embeddings(graph, target_entity_type=entity_type)
        print(f"Computed {len(entity_embeddings)} {entity_type} embeddings.")
        
        for node_idx in graph.node_indices():
            attrs = graph.get_node_data(node_idx)
            if attrs and attrs.get("type") == entity_type and attrs.get("id") in entity_embeddings:
                attrs["embedding"] = entity_embeddings[attrs["id"]]
                graph[node_idx] = attrs

    return graph

def process_graphml_file(input_path: str, output_path: Optional[str] = None):
    """
    Reads a GraphML file, runs the embedding pipeline, and writes the enriched graph back to disk.
    
    Args:
        input_path: Path to the input GraphML file.
        output_path: Path to save the enriched GraphML file. If None, saves as <input_path>_with_embeddings.graphml.
    """
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"Error: {input_path} not found.")

    if output_path is None:
        output_path = input_path.replace(".graphml", "_with_embeddings.graphml")

    print(f"Loading graph from {input_path}...")
    graph = load_graphml_to_rx(input_path)
    print(f"Graph loaded with {graph.num_nodes()} nodes and {graph.num_edges()} edges.")

    graph = run_embedding_pipeline(graph)

    print(f"\nSaving enriched graph to {output_path}...")
    write_rx_to_graphml(graph, output_path)
    print("Done.")

if __name__ == "__main__":
    import typer
    typer.run(process_graphml_file)


