ai2025.jsonl:
	pyalex works --year 2025 --has-abstract --limit 50 --subfield-ids 1702 --select "title_abstract" --jsonl-file ai2025.jsonl

ai2024.jsonl:
	pyalex works --year 2024 --has-abstract --limit 50 --subfield-ids 1702 --select "title_abstract" --jsonl-file ai2024.jsonl
