from abc import ABC, abstractmethod
import rustworkx as rx
import numpy as np

class EntityEmbeddingStrategy(ABC):
    """Base class for strategies that compute embeddings for non-Work entities."""
    
    def __init__(self, model_name: str = "all-MiniLM-L6-v2"):
        self.model_name = model_name

    @abstractmethod
    def compute_embeddings(self, graph: rx.PyGraph | rx.PyDiGraph, target_entity_type: str = "author") -> dict[str, np.ndarray]:
        """
        Takes a rustworkx graph and returns a dictionary mapping Entity IDs 
        (e.g., Author IDs) to their computed embedding vectors.
        
        Args:
            graph: A rustworkx graph generated by pyalex network build.
            target_entity_type: The `entity_type` attribute of the nodes to generate embeddings for (e.g., 'author', 'institution').
            
        Returns:
            Dictionary mapping node IDs (e.g., 'A123456') to numpy arrays.
        """
        pass
